### ISSUE TITLE
COM 장신구 계획

### ISSUE THREAD

**Issue by 115dkk** [115dkk/darkest-dungeon-muskteer-rework-mod#6]
COM 장신구를 다음과 같이 리워크해야 한다.

(1,2열일 경우) 스킬 공격력 +40%, 명중률 +10%, 보호 무시 가능
샷건: 방어력 무시 능력 부여
집중 사격 명중률 -15, 크리율 - 10%
공격 감나빗시 스트레스 +10
스트레스 + 20%

**Comment by Toritae** [comment]
COM장신구의 경우 다키스트 던전 dlc/COM폴더/trinkets폴더내부에 있는데, musketeer 상위폴더인지라.. 추가요청드립니다

**Comment by 115dkk** [comment]
> COM장신구의 경우 다키스트 던전 dlc/COM폴더/trinkets폴더내부에 있는데, musketeer 상위폴더인지라.. 추가요청드립니다

추가 완료했습니다. 해당 브랜치를 contributor branch에 반영해두겠습니다.

**Comment by Toritae** [comment]
'보호 무시'라는 것이 보호받는 몬스터를 보호하는 몹을 무시하되, 보호가 풀리지 않게끔 하는것이 목표인건가요?

**Comment by 115dkk** [comment]
@Toritae 네. 그렇습니다.

**Comment by Toritae** [comment]
보호무시효과는 스킬 타겟 지정시 결정되는 상태로, 닼던연산이 닼던의 장신구(trinkets,buff.json)->info(타겟지정,스킬의대미지계산)->effect[buff](상태이상)순으로 실행 추정, 혹시몰라 effect문의 출혈기술로 방어관통효과로 변경가능할지 테스트중.

**Comment by Toritae** [comment]
보호무시기능은 info파일에서만 적용이 되는 문제점을 토대로, 보호무시의 효과수정 건의를 부탁드립니다.

**Comment by 115dkk** [comment]
> 보호무시기능은 info파일에서만 적용이 되는 문제점을 토대로, 보호무시의 효과수정 건의를 부탁드립니다.

그렇잖아도 뜯어고쳐야겠다는 생각이 들던 참이었습니다. 새 이슈를 만들고 지금 이슈는 이후 닫겠습니다. 수고하셨습니다!

**Comment by 115dkk** [comment]
덤으로, 해당 보호무시 기능은 정말 무쓸모 스킬이라고 욕먹는 권총사격에 기본 사양으로 붙여두기라도 해야 할 것 같습니다. 그래도 COM 없이는 쓸모없겠지만요.

**Comment by 115dkk** [comment]
https://github.com/115dkk/darkest-dungeon-muskteer-rework-mod/issues/16
